name: Build UPM .zip

on:
  push:
    tags:
      - versions/v*
  workflow_dispatch:

jobs:
  release-upm:
    runs-on: ubuntu-latest
    environment: publish
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/versions/v')
    permissions:
      # Required to create release
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Run packaging
        shell: bash
        env:
          GHA_OUTPUT_GROUPS: "1"
        run: |
          python DevOps/package_distribution.py

      - name: Publish UPM package as release artifact on GitHub
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          export tag_name="${GITHUB_REF##*/tags/}"

          assets=()
          for asset in ./Builds/*.{zip,unitypackage}; do
            assets+=("$asset")
          done

          tag_name="${GITHUB_REF##*/tags/}"
          gh release create "${tag_name}" --draft --title "${tag_name}" --notes-file ./Builds/RELEASE_SUMMARY.md "${assets[@]}"
          gh release edit "${tag_name}" --draft=false
